ALTER TABLE Produto
ADD CONSTRAINT vl_max CHECK(CAST(vl_sugeridoproduto as int) <= 1000)

SELECT * FROM PRODUTO WHERE CD_PRODUTO < 6

UPDATE PRODUTO
SET VL_SUGERIDOPRODUTO = 500
WHERE CD_PRODUTO < 3

SELECT * FROM PRODUTO WHERE CD_PRODUTO < 6